### ISSUE TITLE
Notification of session completed still poping if session is closed

### ISSUE THREAD

**Issue by tregnier** [lubenard/oRing_Reminder#3]
The notification that the wearing time is completed on a session is still showing after the time setup, even if the session has been closed early

example :
setting--> wearing time = 1hr

start session at 9:00am
stop the session at 9:30am

At 10:00am, the notification will pop up to notify we can now remove the ring

**Comment by lubenard** [comment]
Hello !
Are you using the latest version ?
This has already fixed in [this](https://github.com/lubenard/oRing_Reminder/commit/9b72d6d1c682b0666f539d22111fd1dd53dddd8c) commit. 

To compile the latest version, you can use it with gradle:
```
./gradlew assemble
```

**Comment by tregnier** [comment]
Hello,
No, only the one from the playstore! Haven't got the time to look at the other upgrade here yet
All good then :) I'll test the latest one when I can
