### ISSUE TITLE
Translatable ?

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [lubenard/oRing_Reminder#7]
![IMG_20211031_121107_060](https://user-images.githubusercontent.com/61406324/139583773-bec9723e-b36f-4623-859c-01530390e04b.jpg)
i see the app is translatable. are there strings for it somewhere?
thanks in advance

**Comment by lubenard** [comment]
Hello, yes the app is translatable ! [This](https://github.com/lubenard/oRing_Reminder/blob/master/app/src/main/res/values/strings.xml) file contains the english string. 

Look for the 2 digits country code you want to add [here](https://www.iban.com/country-codes)

To add a new language, create a folder called ```values-<country code>``` inside the ```app/src/main/res``` folder
Inside this folder, create a file called ```strings.xml```

The code for changing the language is located [here](https://github.com/lubenard/oRing_Reminder/blob/bf48b118550a0a4631500d43526b79f060ee07fd/app/src/main/java/com/lubenard/oring_reminder/ui/SettingsFragment.java#L64) and [here](https://github.com/lubenard/oRing_Reminder/blob/bf48b118550a0a4631500d43526b79f060ee07fd/app/src/main/java/com/lubenard/oring_reminder/utils/Utils.java#L61)

I leave this if it helps : https://developer.android.com/training/basics/supporting-devices/languages

If you are talking about a website hosting translations, sadly no

Thanks for helping !

**Comment by mondlicht-und-sterne** [comment]
here is the german translation

https://github.com/mondlicht-und-sterne/Translations/blob/main/oRing-strings-de.xml

**Comment by lubenard** [comment]
Could you add it as a PR ? That would be fantastic ! Thanks !

**Comment by mondlicht-und-sterne** [comment]
I have sent you a PR.
